application/resume/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

bpResume = Blueprint('bpResume', __name__)

from . import views_JProfile, views_JExperience, views_PExperience, views_PStructure

application/show/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

bpShow = Blueprint('bpShow', __name__)

from . import views

application/show/views.py
# -*- coding: utf-8 -*-

from flask import render_template, url_for, redirect
from playhouse.flask_utils import get_object_or_404
from flask_login import current_user
from ..models import User, Project, Diary, JobProfile, JobExperience, ProjectExperience, ProjectStructure
from . import bpShow

@bpShow.route('/info')
def info():
    try:
        me = User.get(User.id == current_user.id)
        if me:
            user = me
    except:
        user = User.get(User.username == 'lc')

    query = Project.select().join(User).where(User.id == user.id)
    projects = [row for row in query]

    return render_template('show/info.html', user=user, projects=projects)

@bpShow.route('/gallery')
def gallery():
    try:
        me = User.get(User.id == current_user.id)
        if me:
            user = me
    except:
        user = User.get(User.username == 'lc')

    query = Diary.select().join(User).where(User.id == user.id)
    diarys = query

    return render_template('show/gallery.html', user=user, diarys=diarys)

@bpShow.route('/contact')
def contact():
    return render_template('show/contact.html')

@bpShow.route('/resume')
def resume():
    try:
        me = User.get(User.id == current_user.id)
        if me:
            user = me
    except:
        user = User.get(User.username == 'lc')
    query = JobProfile.select().join(User).where(User.id == user.id)
    jobProfiles = query

    query = JobExperience.select().join(User).where(User.id == user.id).order_by(JobExperience.id)
    jobExperiences = query

    query = ProjectExperience.select().join(User).where(User.id == user.id).order_by(ProjectExperience.id)
    projectExperiences = query

    query = ProjectStructure.select().join(User).where(User.id == user.id).order_by(ProjectStructure.id)
    projectStructures = query

    return render_template('show/resume.html', user=user, jobProfiles=jobProfiles, jobExperiences=jobExperiences, projectExperiences=projectExperiences, projectStructures=projectStructures)

application/templates/show/contact.html
{% extends 'show/show_base.html' %}

{% block content_body %}
    <div id="menu-4" class="contact-section">
        <div class="row">
            <div class="col-md-4 col-sm-4">
                <div class="box-content">
                    <ul>
                        <li>
                            <img src="{{ url_for('static', filename='images/me.jpg') }}">
                        </li>
                        <li>
                            <p><b>姓名:</b>鲁成</p>
                        </li>
                        <li>
                            <p><b>出生年月:</b>1996-01-27</p>
                        </li>
                        <li>
                            <p><b>学历:</b>西南林业大学2014级在校生</p>
                        </li>
                        <li>
                            <p><b>电话:</b>184-8730-0572</p>
                        </li>
                        <li>
                            <p><b>邮箱:</b>lc960127@gmail.com</p>
                        </li>
                        <li>
                            <p><b>微信:</b>LC_WeChat_0127</p>
                        </li>
                        <li>
                            <p><b>QQ:</b>1006115980</p>
                        </li>
                        <li>
                            <p><b>Bitbucket:</b><a href="https://bitbucket.org/lucheng0127">bitbucket.org/lucheng0127</a></p>
                        </li>
                        <li>
                            <p><b>GitHub:</b><a href="https://github.org/lucheng001">github.org/lucheng001</a></p>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-8 col-sm-8">
                <div class="box-content">
                    <h3 class="widget-title">Send Us A Message</h3>
                    <form class="contact-form">
                        <fieldset>
                            <input type="text" class="name" id="name" placeholder="Name...">
                        </fieldset>
                        <fieldset>
                            <input type="email" class="email" id="email" placeholder="Email...">
                        </fieldset>
                        <fieldset>
                            <input type="text" class="subject" id="subject" placeholder="Subject...">
                        </fieldset>
                        <fieldset>
                            <textarea name="message" id="message" cols="30" rows="4" placeholder="Message.."></textarea>
                        </fieldset>
                        <fieldset>
                            <input type="submit" class="button" id="button" value="Send Message">
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

application/templates/show/gallery.html
{% extends 'show/show_base.html' %}

{% block content_body %}
    <div class="gallery-section">
        <div class="box-content">
            <div class="row">
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <h3 class="widget-title">Photos</h3>
                    <div class="project-item">
                        <img src="{{ url_for('static', filename='images/rockclimbing.jpg') }}" alt="">
                        <div class="project-hover">
                            <h4>抱石训练</h4>
                        </div>
                    </div>
                    <div class="project-item">
                        <img src="{{ url_for('static', filename='images/mountainclimb.jpg') }}" alt="">
                        <div class="project-hover">
                            <h4>2016雪花勇闯天涯</h4>
                        </div>
                    </div>
                    <div class="project-item">
                        <img src="{{ url_for('static', filename='images/kickboxingtraining.jpg') }}" alt="">
                        <div class="project-hover">
                            <h4>曾经的对练</h4>
                        </div>
                    </div>
                    <div class="text-center">
                        <ul>
                            <li><a href="#" class="fa fa-refresh"></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <h3 class="widget-title">It's my life ! <a href="{{ url_for('bpDiary.addDiary') }}" class="fa fa-pencil"></a></h3>
                    {% for diary in diarys %}
                         <div class="project-item">
                            <div class="col-md-8">
                                <label>
                                    {{ diary.body }}
                                </label>
                                <div class="col-md-2"></div>
                                <div class="col-md-8">
                                    {% if diary.havePhoto %}
                                        <img src="{{ url_for('static', filename=diary.photoURL ) }}" alt="">
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <p>{{ diary.createTime }}</p>
                                <a href="{{ url_for('bpDiary.delectDiary', diaryId=diary.id) }}" class="fa fa-trash"></a>
                            </div>
                        </div>
                        <br>
                    {% endfor %}
                    <div class="project-pages">
                        <ul>
                            <li><a href="#" class="fa fa-arrow-left"></a> </li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#" class="fa fa-arrow-right"></a> </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

application/templates/show/home.html
{% extends 'show/show_base.html' %}

{% block content_body %}
    <div class="logo-holder logo-top-margin">
        <a href="{{ url_for('bpShow.info') }}" class="site-brand"><img src="{{ url_for('static', filename='images/logo.jpg') }}"></a>
    </div>
    <div id="menu-1" class="homepage home-section text-center">
        <div class="welcome-text">
            <h2>Welcome to <strong>wolf space</strong></h2>
            <p>(Like Python || ArchLinux || kickboxing || rocking climbing || swimming || outdoors)?</p>
            <p>Get in touch with me : Just look through or leave</p>
            <br>
            <br>
            <p><b>Know more about me:</b></p>
            <br>
            <a href="{{ url_for('bpShow.info') }}" class="btn btn-primary">Next-></a>
        </div>
    </div>
{% endblock %}

application/templates/show/info.html
{% extends 'show/show_base.html' %}

{% block content_body %}
    <div class="about-section">
        <div class="row">
            <div class="col-md-8 col-sm-8">
                <div class="profile">
                    <div class="col-md-4">
                        <a href="{{ url_for('bpUser.resetProfile') }}"><img src="{{ url_for('static', filename='images/me.jpg') }}" alt=""></a>
                        <br>
                        <br>
                        <p class="text-center">{{ user.aboutMe }}</p>
                    </div>
                    <div class="col-md-7">
                        <h5 class="profile-name">{{ user.chinesename }}</h5>
                        <br>
                        <span class="blue">求职意向及简历详见：<a href="{{ url_for('bpShow.resume') }}"><i class="fa fa-paperclip btn btn-link">我的简历</i> </a> </span>
                        <br>
                        <br>
                        <p>I'm one of the SWFU, major in The Communication Engineering, with time goes by I found maybe I should be a programmer rather than do what like what we been taught like that after graduation try to be a postgraduate,
                        and then try to be a member of government, this not my life. You Only Live Once! why not make your life be colorful?</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-4">
                <img src="{{ url_for('static', filename='images/arch-python_logo.png') }}">
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <div class="box-content">
                    <h3 class="widget-title">My Technical Skills</h3>
                    <div class="project-item">
                        <p>
                            <label>Python:</label><br>
                            Can independently finish a Web project using Flask.And knew some frequently used development plugin.<br>
                        </p>
                    </div>
                    <br>
                    <div class="project-item">
                        <p>
                            <label>Linux:</label><br>
                            Up to now I have been used Linux as my PC system for 2 years, in the past I had tried Ubuntu, Debian, OpenSuse, FreeBSD and now ArchLinux, in it ArchLinux is a prefect OS for PC, and FreeBSD is a excellent OS for service.<br>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-6">
                <div class="box-content">
                    <h3 class="widget-title">My Project Experience   |    <a href="{{ url_for('bpProject.addProject') }}" class="fa fa-plus"></a></h3>
                    <p>What I mean a true experience of project.</p>
                    <label>Bitbucket:</label>
                    <a href="https://bitbucket.org/lucheng0127">https://bitbucket.org/lucheng0127</a>
                    {% if projects %}
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>项目名称</th>
                                    <th>项目负责人</th>
                                    <th>项目总结</th>
                                </tr>
                            </thead>
                        <tbody>
                            {% for project in projects %}
                                <tr>
                                    <th>{{ project.name }}</th>
                                    <th>{{ project.author.chinesename }}</th>
                                    <th>
                                        {% if current_user.is_authenticated  %}
                                            <a href="{{ url_for('bpProject.delete', projectId=project.id) }}" class="fa fa-trash"></a>
                                            <a href="{{ url_for('bpProject.upload', projectId=project.id) }}" class="fa fa-upload"></a>
                                        {% endif %}
                                            <a href="{{ url_for('bpProject.download', projectId=project.id) }}" class="fa fa-download"></a>
                                    </th>
                                </tr>
                            {% endfor %}
                        </tbody>
                        </table>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

application/templates/show/resume.html
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<head>
    <title>My resume</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Global CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <!-- Plugins CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.css') }}">

    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <div class="wrapper">
        <div class="sidebar-wrapper">
            <div class="profile-container">
                <a href="{{ url_for('bpShow.info') }}"><img class="profile" src="{{ url_for('static', filename='images/meSmall.jpg') }}" alt="" /></a>
                <h1 class="name">{{ user.chinesename }}</h1>
                <h5>1996-01-27</h5>
            </div><!--//profile-container-->

            <div class="contact-container container-block">
                <ul class="list-unstyled contact-list">
                    <li class="email"><i class="fa fa-envelope"></i><p>{{ user.email }}</p></li>
                    <li class="phone"><i class="fa fa-phone"></i><p>{{ user.tel }}</p></li>
                    <li><i class="fa fa-bitbucket"></i><a href="https://bitbucket.org/lucheng0127">bitbucket.org/lucheng0127</a></li>
                    <li><i class="fa fa-wechat"></i><a href="#" target="_blank">LC_WeChat_0127</a></li>
                    <li class="github"><i class="fa fa-github"></i><a href="https://github.com/lucheng001/" target="_blank">github.com/lucheng001</a></li>
                </ul>
            </div><!--//contact-container-->
            <div class="education-container container-block">
                <h2 class="container-block-title">Education</h2>
                <div class="item">
                    <h4 class="degree">专业:通信工程</h4>
                    <h5 class="meta">西南林业大学</h5>
                    <div class="time">2014入学</div>
                </div><!--//item-->
            </div><!--//education-container-->

            <div class="languages-container container-block">
                <h2 class="container-block-title">Languages</h2>
                <ul class="list-unstyled interests-list">
                    <li>Chinese <span class="lang-desc">(Native)</span></li>
                    <li>English <span class="lang-desc">(Not bad)</span></li>
                </ul>
            </div><!--//interests-->

            <div class="interests-container container-block">
                <h2 class="container-block-title">Interests</h2>
                <ul class="list-unstyled interests-list">
                    <li>KickBoxing</li>
                    <li>Swimming</li>
                    <li>Rock Climbing</li>
                </ul>
            </div><!--//interests-->

        </div><!--//sidebar-wrapper-->

        <div class="main-wrapper">

            <section class="section summary-section">
                <h2 class="section-title"><i class="fa fa-user"></i>求职意向{% if current_user.is_authenticated %}<a href="{{ url_for('bpResume.addJProfile') }}" class="fa fa-plus"></a>{% endif %}</h2>
                <div class="summary">
                    <p>
                        {% for jobProfile in jobProfiles %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('bpResume.editJProfile', jobProfileId=jobProfile.id) }}" class="fa fa-pencil"></a>
                            {% endif %}
                            <p><b>目标职能：</b>{{ jobProfile.job }}</p>
                            <p><b>工作性质：</b>{{ jobProfile.jobType }}</p>
                            <p><b>期望月薪：</b>{{ jobProfile.salary }}</p>
                        {% endfor %}
                    </p>
                </div><!--//summary-->
            </section><!--//section-->

            <section class="section experiences-section">
                <h2 class="section-title"><i class="fa fa-briefcase"></i>相关经验{% if current_user.is_authenticated %}<a href="{{ url_for('bpResume.addJExperience') }}" class="fa fa-plus"></a>{% endif %}</h2>
                {% for jobExperience in jobExperiences %}
                    <div class="item">
                        <div class="meta">
                            <div class="upper-row">
                                <h3 class="job-title">{{ jobExperience.theme }}{% if current_user.is_authenticated %}<a href="{{ url_for('bpResume.deleteJExperience', jExperienceId=jobExperience.id) }}" class="fa fa-trash"></a>{% endif %}</h3>
                                <div class="time">{{ jobExperience.time }}</div>
                            </div><!--//upper-row-->
                            <div class="company">{{ jobExperience.location }}</div>
                        </div><!--//meta-->
                        <div class="details">
                            <p>
                                {{ jobExperience.body }}
                            </p>
                        </div><!--//details-->
                    </div><!--//item-->
                {% endfor %}
            </section><!--//section-->

            <section class="section projects-section">
                <h2 class="section-title"><i class="fa fa-archive"></i>项目经历{% if current_user.is_authenticated %}<a href="{{ url_for('bpResume.addPExperience') }}" class="fa fa-plus"></a> {% endif %}</h2>
                <div class="intro">
                    <p>此项目经历指的是经过测试并可对外开放使用的项目，并非课堂上随便做做的那种。</p>
                </div><!--//intro-->
                {% for projectExperience in projectExperiences %}
                    <div class="item">
                        <span class="project-title"><a target="_blank">{% if current_user.is_authenticated %}<a href="{{ url_for('bpResume.deletePExperience', pExperienceId=projectExperience.id) }}" class="fa fa-trash"></a>{% endif %}{{ projectExperience.name }}</a></span> -
                        <span class="project-tagline">{{ projectExperience.body }}</span>
                    </div><!--//item-->
                {% endfor %}
            </section><!--//section-->

            <section class="skills-section section">
                <h2 class="section-title"><i class="fa fa-rocket"></i>技能结构{% if current_user.is_authenticated %}<a href="{{ url_for('bpResume.addPStructure') }}" class="fa fa-plus"></a> {% endif %}</h2>
                <div class="skillset">
                    {% for projectStructure in projectStructures %}
                        <div class="item">
                        <h3 class="level-title">{% if current_user.is_authenticated %}<a href="{{ url_for('bpResume.deletePStructure', pStructureId=projectStructure.id) }}" class="fa fa-trash"></a>{% endif %}{{ projectStructure.name }}</h3>
                        <div class="level-bar">
                            <div class="level-bar-inner" style="width: {{ projectStructure.pdate }}%;">
                            </div>
                        </div><!--//level-bar-->
                    </div><!--//item-->
                    {% endfor %}
                </div>
            </section><!--//skills-section-->

        </div><!--//main-body-->
    </div>

    <footer class="footer">
        <div class="text-center">
                <small class="copyright">Copyright &copy; 2016 lucheng  |  mail: lc960127@gmail.com  |   WeChat:  LC_WeChat_0127   |  Bitbucket: <a href="https://bitbucket.org/lucheng0127">https://bitbucket.org/lucheng0127</a></small>
        </div><!--//container-->
    </footer><!--//footer-->

    <!-- Javascript -->
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-1.11.3.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <!-- custom js -->
    <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>
</html>

application/templates/show/show_base.html
{% extends 'base.html' %}

{% block page_content %}
    <div class="col-md-9 col-sm-12 content-holder">
        <div id="menu-container">
            {% block content_body %}{% endblock %}
        </div>
    </div>

    <div class="col-md-3 hidden-sm">
        <nav id="nav" class="main-navigation hidden-xs hidden-sm">
            <ul class="main-menu">
                <li class="homebutton">
                    <a href="{{ url_for('bpShow.info') }}"><i class="fa fa-user"></i>About Me</a>
                </li>
                <li class="projectbutton">
                    <a href="{{ url_for('bpShow.gallery') }}"><i class="fa fa-camera"></i>Gallery</a>
                </li>
                <li class="aboutbutton">
                    <a href="{{ url_for('bpShow.resume') }}"><i class="fa fa-paperclip"></i>Resume</a>
                </li>
                <li class="contactbutton">
                    <a href="{{ url_for('bpShow.contact') }}"><i class="fa fa-envelope"></i>Contact</a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}