application/diary/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import Form
from wtforms import TextAreaField, SelectField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField

_all_=['addProjectDataForm', 'addProjectForm']

class addDiaryForm(Form):
    diaryData = TextAreaField(
        u'日记',
        validators=[
            DataRequired(u'日记能为空')
        ]
    )

    photo = FileField(u'图片')

class addDiaryDataForm(Form):
    body = TextAreaField(
        u'日记内容',
        validators=[
            DataRequired(u'日记内容不能为空')
        ]
    )

    author = SelectField(
        u'作者',
        validators=[
            DataRequired(u'作者不能为空')
        ]
    )

application/diary/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

bpDiary = Blueprint('bpDiary', __name__)

from . import views

application/diary/views.py
# -*- coding: utf-8 -*-

import os
import shutil
from flask import render_template, url_for, redirect, flash, current_app, abort
from flask_login import current_user, login_required
from playhouse.flask_utils import get_object_or_404
from werkzeug.utils import secure_filename
from ..models import User, Diary
from .forms import addDiaryForm, addDiaryDataForm
from . import bpDiary

@bpDiary.route('/writeDairy', methods=['GET', 'POST'])
@login_required
def addDiary():
    form = addDiaryForm()
    if form.validate_on_submit():
        query = (User.select(User.id, User.chinesename))
        authors = [row for row in query]
        diaryForm = addDiaryDataForm()
        fExtension = u'unknown'
        secureFileName = secure_filename(form.photo.data.filename)

        if secureFileName:
            res = secureFileName.rsplit('.', 1)
            if len(res) == 2:
                fExtension = res[1]
            else:
                fExtension = res[0]

        if form.photo.data:
            diaryDic = dict(
                body=form.diaryData.data,
                author=current_user.id,
                havePhoto=1,
                fExtension=fExtension
            )
            photoName = u'{body}.{fExtension}'.format(**diaryDic)
            photoPath = current_app.config['APP_DIARY_PHOTO_DIR']
            form.photo.data.save(os.path.join(photoPath, photoName))
            diaryDic = dict(
                body=form.diaryData.data,
                author=current_user.id,
                havePhoto=1,
                fExtension=fExtension,
                photoURL=u'diaryPhoto/{}'.format(photoName)
            )
        else:
            diaryDic = dict(
                body=form.diaryData.data,
                author=current_user.id,
                havePhoto=0
            )


        diaryForm.author.choices = [(author.id, author.chinesename) for author in authors]
        diaryForm.author.data = diaryDic['author']
        diaryForm.body.data = diaryDic['body']

        if not diaryForm.validate():
            flash(u'写入失败!', 'error')
            return redirect(url_for('bpShow.gallery'))

        Diary.create(**diaryDic)
        return redirect(url_for('bpShow.gallery'))
    return render_template('show/diary/addDiary.html', form=form)

@bpDiary.route('/rmDiary/<int:diaryId>', methods=['GET'])
@login_required
def delectDiary(diaryId):
    diary = get_object_or_404(Diary, Diary.id == diaryId)
    if not current_user.id == diary.author.id:
        abort(403)

    if diary.havePhoto:
        photoPath = current_app.config['APP_STATIC_DIR']
        photoName = diary.photoURL
        filePath = os.path.join(photoPath, photoName)
        if os.path.isfile(filePath):
            os.remove(filePath)

    diary.delete_instance()
    return redirect(url_for('bpShow.gallery'))

application/show/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

bpShow = Blueprint('bpShow', __name__)

from . import views

application/show/views.py
# -*- coding: utf-8 -*-

from flask import render_template, url_for, redirect
from playhouse.flask_utils import get_object_or_404
from flask_login import current_user
from ..models import User, Project, Diary, JobProfile, JobExperience, ProjectExperience, ProjectStructure
from . import bpShow

@bpShow.route('/info')
def info():
    try:
        me = User.get(User.id == current_user.id)
        if me:
            user = me
    except:
        user = User.get(User.username == 'lc')

    query = Project.select().join(User).where(User.id == user.id)
    projects = [row for row in query]

    return render_template('show/info.html', user=user, projects=projects)

@bpShow.route('/gallery')
def gallery():
    try:
        me = User.get(User.id == current_user.id)
        if me:
            user = me
    except:
        user = User.get(User.username == 'lc')

    query = Diary.select().join(User).where(User.id == user.id)
    diarys = query

    return render_template('show/gallery.html', user=user, diarys=diarys)

@bpShow.route('/contact')
def contact():
    return render_template('show/contact.html')

@bpShow.route('/resume')
def resume():
    try:
        me = User.get(User.id == current_user.id)
        if me:
            user = me
    except:
        user = User.get(User.username == 'lc')
    query = JobProfile.select().join(User).where(User.id == user.id)
    jobProfiles = query

    query = JobExperience.select().join(User).where(User.id == user.id).order_by(JobExperience.id)
    jobExperiences = query

    query = ProjectExperience.select().join(User).where(User.id == user.id).order_by(ProjectExperience.id)
    projectExperiences = query

    query = ProjectStructure.select().join(User).where(User.id == user.id).order_by(ProjectStructure.id)
    projectStructures = query

    return render_template('show/resume.html', user=user, jobProfiles=jobProfiles, jobExperiences=jobExperiences, projectExperiences=projectExperiences, projectStructures=projectStructures)

application/templates/show/diary/addDiary.html
{% extends 'base.html' %}

{% block page_content %}
    <div class="logo-holder logo-top-margin">
        <a href="{{ url_for('bpShow.gallery') }}" class="site-brand"><img src="{{ url_for('static', filename='images/logo.jpg') }}"></a>
    </div>
    <div class="container">
        <div class="row">
            {% with messages = get_flashed_messages(with_categories = True) %}
            {% if messages %}
                {% for category, message in messages %}
                    <span class="text-danger"><b>{{ category }}:</b>{{ message }}</span>
                {% endfor %}
            {% endif %}
            {% endwith %}
            <div class="col-md-12 text-center">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <h1>write something today:</h1>
                </div>
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div>
                    <form method="post" action="{{ url_for('bpDiary.addDiary') }}" enctype="multipart/form-data">
                        {{ form.csrf_token }}
                        <textarea name="diaryData" rows="5" class="form-control" required></textarea>
                        {{ form.photo }}
                        <button class="btn btn-primary" type="submit">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}